#ifndef _SYMBOL_H
#define _SYMBOL_H

#define SYMBOL_CATCH_STAR "catch*"
#define SYMBOL_CONCAT "concat"
#define SYMBOL_CONS "cons"
#define SYMBOL_DEF_BANG "def!"
#define SYMBOL_DEFMACRO "defmacro!"
#define SYMBOL_DEREF "deref"
#define SYMBOL_DO "do"
#define SYMBOL_FALSE "false"
#define SYMBOL_FN_STAR "fn*"
#define SYMBOL_IF "if"
#define SYMBOL_LET_STAR "let*"
#define SYMBOL_MACRO_EXPAND "macroexpand"
#define SYMBOL_NIL "nil"
#define SYMBOL_QUOTE "quote"
#define SYMBOL_QUASI_QUOTE "quasiquote"
#define SYMBOL_QUASI_QUOTE_EXPAND "quasiquoteexpand"
#define SYMBOL_QUOTE "quote"
#define SYMBOL_SPLICE_UNQUOTE "splice-unquote"
#define SYMBOL_TRUE "true"
#define SYMBOL_TRY_STAR "try*"
#define SYMBOL_UNQUOTE "unquote"
#define SYMBOL_VEC "vec"
#define SYMBOL_WITH_META "with-meta"
#endif